import { Injectable } from '@angular/core';

@Injectable()
export class Utilities {
    static getStates(): any {
        return [
            { StateCode: 'AL', Name: 'Alabama' },
            { StateCode: 'AK', Name: 'Alaska' },
            { StateCode: 'AZ', Name: 'Arizona' },
            { StateCode: 'AR', Name: 'Arkansas' },
            { StateCode: 'CA', Name: 'California' },
            { StateCode: 'CO', Name: 'Colorado' },
            { StateCode: 'CT', Name: 'Connecticut' },
            { StateCode: 'DE', Name: 'Delaware' },
            { StateCode: 'FL', Name: 'Florida' },
            { StateCode: 'GA', Name: 'Georgia' },
            { StateCode: 'HI', Name: 'Hawaii' },
            { StateCode: 'ID', Name: 'Idaho' },
            { StateCode: 'IL', Name: 'Illinois' },
            { StateCode: 'IN', Name: 'Indiana' },
            { StateCode: 'IA', Name: 'Iowa' },
            { StateCode: 'KS', Name: 'Kansas' },
            { StateCode: 'KY', Name: 'Kentucky' },
            { StateCode: 'LA', Name: 'Louisiana' },
            { StateCode: 'ME', Name: 'Maine' },
            { StateCode: 'MD', Name: 'Maryland' },
            { StateCode: 'MA', Name: 'Massachusetts' },
            { StateCode: 'MI', Name: 'Michigan' },
            { StateCode: 'MN', Name: 'Minnesota' },
            { StateCode: 'MS', Name: 'Mississippi' },
            { StateCode: 'MO', Name: 'Missouri' },
            { StateCode: 'MT', Name: 'Montana' },
            { StateCode: 'NE', Name: 'Nebraska' },
            { StateCode: 'NV', Name: 'Nevada' },
            { StateCode: 'NH', Name: 'New Hampshire' },
            { StateCode: 'NJ', Name: 'New Jersey' },
            { StateCode: 'NM', Name: 'New Mexico' },
            { StateCode: 'NY', Name: 'New York' },
            { StateCode: 'NC', Name: 'North Carolina' },
            { StateCode: 'ND', Name: 'North Dakota' },
            { StateCode: 'OH', Name: 'Ohio' },
            { StateCode: 'OK', Name: 'Oklahoma' },
            { StateCode: 'OR', Name: 'Oregon' },
            { StateCode: 'PA', Name: 'Pennsylvania' },
            { StateCode: 'RI', Name: 'Rhode Island' },
            { StateCode: 'SC', Name: 'South Carolina' },
            { StateCode: 'SD', Name: 'South Dakota' },
            { StateCode: 'TN', Name: 'Tennessee' },
            { StateCode: 'TX', Name: 'Texas' },
            { StateCode: 'UT', Name: 'Utah' },
            { StateCode: 'VT', Name: 'Vermont' },
            { StateCode: 'VA', Name: 'Virginia' },
            { StateCode: 'WA', Name: 'Washington' },
            { StateCode: 'WV', Name: 'West Virginia' },
            { StateCode: 'WI', Name: 'Wisconsin' },
            { StateCode: 'WY', Name: 'Wyoming' },
            { StateCode: 'AS', Name: 'American Samoa' },
            { StateCode: 'DC', Name: 'District of Columbia' },
            { StateCode: 'FM', Name: 'Federated States of Micronesia' },
            { StateCode: 'MH', Name: 'Marshall Islands' },
            { StateCode: 'MP', Name: 'Northern Mariana Islands' },
            { StateCode: 'PW', Name: 'Palau' },
            { StateCode: 'PR', Name: 'Puerto Rico' },
            { StateCode: 'VI', Name: 'Virgin Islands' },
            { StateCode: 'GU', Name: 'Guam' }
        ];
    }


    static getServiceCategories(): any {
        return [
            { 'id': 1, 'name': 'Home Service' },
            { 'id': 2, 'name': 'Lawn/Garden', 'parentId': 1 },
            { 'id': 3, 'name': 'Living Room ', 'parentId': 1 },
            { 'id': 4, 'name': 'Bedroom', 'parentId': 1 },
            { 'id': 5, 'name': 'Roofing/Gutters', 'parentId': 1 },
            { 'id': 6, 'name': 'Lightening', 'parentId': 1 },
            { 'id': 7, 'name': 'Concrete work', 'parentId': 1 },
            { 'id': 8, 'name': 'Snow removal ', 'parentId': 1 },
            { 'id': 9, 'name': 'Interior decorator', 'parentId': 1 },
            { 'id': 10, 'name': 'Electrical', 'parentId': 1 },
            { 'id': 11, 'name': 'Garage', 'parentId': 1 },
            { 'id': 12, 'name': 'Home designer', 'parentId': 1 },
            { 'id': 13, 'name': 'Wood working', 'parentId': 1 },
            { 'id': 14, 'name': 'Pest Control', 'parentId': 1 },
            { 'id': 15, 'name': 'Dog sitting ', 'parentId': 1 },
            { 'id': 16, 'name': 'Carpet cleaning', 'parentId': 1 },
            { 'id': 17, 'name': 'Painting ', 'parentId': 1 },
            { 'id': 18, 'name': 'Air Conditioning', 'parentId': 1 },
            { 'id': 19, 'name': 'Swimming pool', 'parentId': 1 },
            { 'id': 20, 'name': 'Farm work', 'parentId': 1 },
            { 'id': 21, 'name': 'General laborer', 'parentId': 1 },
            { 'id': 22, 'name': 'Fences', 'parentId': 1 },
            { 'id': 23, 'name': 'Tile Floor', 'parentId': 1 },
            { 'id': 24, 'name': 'Hardwood floor', 'parentId': 1 },
            { 'id': 25, 'name': 'Tiling', 'parentId': 1 },
            { 'id': 26, 'name': 'Masonry', 'parentId': 1 },
            { 'id': 27, 'name': 'Insulation', 'parentId': 1 },
            { 'id': 28, 'name': 'Interior Shutters', 'parentId': 1 },
            { 'id': 29, 'name': 'Attic Stairs', 'parentId': 1 },
            { 'id': 30, 'name': 'Siding', 'parentId': 1 },
            { 'id': 31, 'name': 'Evaporative coolers', 'parentId': 1 },
            { 'id': 32, 'name': 'Generators', 'parentId': 1 },
            { 'id': 33, 'name': 'Ceiling Fan', 'parentId': 1 },
            { 'id': 34, 'name': 'Doors', 'parentId': 1 },
            { 'id': 35, 'name': 'Windows', 'parentId': 1 },
            { 'id': 36, 'name': 'Fencing', 'parentId': 1 },
            { 'id': 37, 'name': 'Gutters', 'parentId': 1 },
            { 'id': 38, 'name': 'HVAC', 'parentId': 1 },
            { 'id': 39, 'name': 'Outdoor Storage install', 'parentId': 1 },
            { 'id': 40, 'name': 'Kitchens' },
            { 'id': 41, 'name': 'Cabinets', 'parentId': 40 },
            { 'id': 42, 'name': 'Bathroom' },
            { 'id': 43, 'name': 'Faucet', 'parentId': 42 },
            { 'id': 44, 'name': 'Toilets', 'parentId': 42 },
            { 'id': 45, 'name': 'Bathtubs', 'parentId': 42 },
            { 'id': 46, 'name': 'Showers', 'parentId': 42 },
            { 'id': 47, 'name': 'Shower & Tub doors', 'parentId': 42 },
            { 'id': 48, 'name': 'Motocycle' },
            { 'id': 49, 'name': 'Diagnostic', 'parentId': 48 },
            { 'id': 50, 'name': 'Service/installation (parts)', 'parentId': 48 },
            { 'id': 51, 'name': 'Audio/Video', 'parentId': 48 },
            { 'id': 52, 'name': 'Medical Equipment' },
            { 'id': 53, 'name': 'Diagnostic', 'parentId': 52 },
            { 'id': 54, 'name': 'Parts Service/ Installation', 'parentId': 52 },
            { 'id': 55, 'name': 'Heavy Equipment' },
            { 'id': 56, 'name': 'Diagnostic', 'parentId': 55 },
            { 'id': 57, 'name': 'Parts Service/Install', 'parentId': 55 },
            { 'id': 58, 'name': 'Air Craft' },
            { 'id': 59, 'name': 'Diagnostic', 'parentId': 58 },
            { 'id': 60, 'name': 'Parts Installation/Service', 'parentId': 58 },
            { 'id': 61, 'name': 'Electrical', 'parentId': 58 },
            { 'id': 62, 'name': 'Metal Fabrication' },
            { 'id': 63, 'name': 'Welding', 'parentId': 62 },
            { 'id': 64, 'name': 'Fabrication', 'parentId': 62 },
            { 'id': 65, 'name': 'Business/Industrial' },
            { 'id': 66, 'name': 'Office renovation', 'parentId': 65 },
            { 'id': 67, 'name': 'Electrical/Equipment', 'parentId': 65 },
            { 'id': 68, 'name': 'Plumbing', 'parentId': 65 },
            { 'id': 69, 'name': 'Semi-Truck/ RV' },
            { 'id': 70, 'name': 'Diagnostic', 'parentId': 69 },
            { 'id': 71, 'name': 'Parts Service/Installation', 'parentId': 69 },
            { 'id': 72, 'name': 'Audio/Video', 'parentId': 69 },
            { 'id': 73, 'name': 'Automotive' },
            { 'id': 74, 'name': 'Diagnostic', 'parentId': 73 },
            { 'id': 75, 'name': 'Parts Service/Installation', 'parentId': 73 },
            { 'id': 76, 'name': 'Audio/Video', 'parentId': 73 },
            { 'id': 77, 'name': 'Arts & Craft' },
            { 'id': 78, 'name': 'Tailor', 'parentId': 77 },
            { 'id': 79, 'name': 'Pottery', 'parentId': 77 },
            { 'id': 80, 'name': 'Wood Carving', 'parentId': 77 },
            { 'id': 81, 'name': 'Origami', 'parentId': 77 },
            { 'id': 82, 'name': 'Glass Art', 'parentId': 77 },
            { 'id': 83, 'name': 'Beadwork', 'parentId': 77 },
            { 'id': 84, 'name': 'Painting', 'parentId': 77 },
            { 'id': 85, 'name': 'Knitting', 'parentId': 77 },
            { 'id': 86, 'name': 'Digital', 'parentId': 77 },
            { 'id': 87, 'name': 'Scrapbooking', 'parentId': 77 },
            { 'id': 88, 'name': 'Photography', 'parentId': 77 },
            { 'id': 89, 'name': 'Studio Craft', 'parentId': 77 },
            { 'id': 90, 'name': 'Sculpting', 'parentId': 77 },
            { 'id': 91, 'name': 'Gadget' },
            { 'id': 92, 'name': 'Desktop Computer', 'parentId': 91 },
            { 'id': 93, 'name': 'Laptop Computer', 'parentId': 91 },
            { 'id': 94, 'name': 'Tablets', 'parentId': 91 },
            { 'id': 95, 'name': 'Mp3 Device', 'parentId': 91 },
            { 'id': 96, 'name': 'Game Console', 'parentId': 91 },
            { 'id': 97, 'name': 'Wii', 'parentId': 91 },
            { 'id': 98, 'name': 'Xbox', 'parentId': 91 },
            { 'id': 99, 'name': 'Game Controller', 'parentId': 91 },
            { 'id': 100, 'name': 'Watches', 'parentId': 91 },
            { 'id': 101, 'name': 'Phones', 'parentId': 91 },
            { 'id': 102, 'name': 'Monitors', 'parentId': 91 },
            { 'id': 103, 'name': 'Headphones', 'parentId': 91 },
            { 'id': 104, 'name': 'Microphones', 'parentId': 91 },
            { 'id': 105, 'name': 'Large Screen TV', 'parentId': 91 },
            { 'id': 106, 'name': 'DVD players', 'parentId': 91 },
            { 'id': 107, 'name': 'Scanners', 'parentId': 91 },
            { 'id': 108, 'name': 'Printers', 'parentId': 91 },
            { 'id': 109, 'name': 'Joystick', 'parentId': 91 },
            { 'id': 110, 'name': 'Hair Dryer', 'parentId': 91 },
            { 'id': 111, 'name': 'Projectors', 'parentId': 91 },
            { 'id': 112, 'name': 'Webcam', 'parentId': 91 },
            { 'id': 113, 'name': 'Radio', 'parentId': 91 },
            { 'id': 114, 'name': 'Type writers', 'parentId': 91 },
            { 'id': 115, 'name': 'Calculators', 'parentId': 91 },
            { 'id': 116, 'name': 'Fax machine', 'parentId': 91 },
            { 'id': 117, 'name': 'Barcode readers', 'parentId': 91 },
            { 'id': 118, 'name': 'Remote Control', 'parentId': 91 },
            { 'id': 119, 'name': 'Power Supply', 'parentId': 91 },
            { 'id': 120, 'name': 'Cameras', 'parentId': 91 },
            { 'id': 121, 'name': 'Piano/Keyboards', 'parentId': 91 },
            { 'id': 122, 'name': 'Toys', 'parentId': 91 },
            { 'id': 123, 'name': 'Wireless Routers', 'parentId': 91 },
            { 'id': 124, 'name': 'Humidifier', 'parentId': 91 },
            { 'id': 125, 'name': 'Satellites', 'parentId': 91 },
            { 'id': 126, 'name': 'Blood Pressure Machines', 'parentId': 91 },
            { 'id': 127, 'name': 'Exercise Machine', 'parentId': 91 },
            { 'id': 128, 'name': 'Theater Receivers', 'parentId': 91 },
            { 'id': 129, 'name': 'Apple TV', 'parentId': 91 },
            { 'id': 130, 'name': 'Digital Mono light', 'parentId': 91 },
            { 'id': 131, 'name': 'Power Recliner Chairs', 'parentId': 91 },
            { 'id': 132, 'name': 'Washing Machine', 'parentId': 91 },
            { 'id': 133, 'name': 'Drying Machine', 'parentId': 91 },
            { 'id': 134, 'name': 'Hair dryer', 'parentId': 91 },
            { 'id': 135, 'name': 'Sewing Machine', 'parentId': 91 },
            { 'id': 136, 'name': 'Scooters', 'parentId': 91 },
            { 'id': 137, 'name': 'VCR Players', 'parentId': 91 },
            { 'id': 138, 'name': 'Turn table', 'parentId': 91 },
            { 'id': 139, 'name': 'Music Box', 'parentId': 91 },
            { 'id': 140, 'name': 'Juke Box', 'parentId': 91 },
            { 'id': 141, 'name': 'Dish Washer', 'parentId': 91 },
            { 'id': 142, 'name': 'Vacuum Cleaner', 'parentId': 91 },
            { 'id': 143, 'name': 'Electric Bed', 'parentId': 91 },
            { 'id': 144, 'name': 'Refrigerators', 'parentId': 91 },
            { 'id': 145, 'name': 'TV Wall Mount', 'parentId': 91 },
            { 'id': 146, 'name': 'Auto GPS', 'parentId': 91 },
            { 'id': 147, 'name': 'Auto Stereo', 'parentId': 91 },
            { 'id': 148, 'name': 'Auto Speakers', 'parentId': 91 },
            { 'id': 149, 'name': 'Auto Sirius', 'parentId': 91 },
            { 'id': 150, 'name': 'Auto Climate Control', 'parentId': 91 },
            { 'id': 151, 'name': 'Auto Subwoofers', 'parentId': 91 },
            { 'id': 152, 'name': 'Auto Steering Wheel', 'parentId': 91 },
            { 'id': 153, 'name': 'Auto electrical', 'parentId': 91 },
            { 'id': 154, 'name': 'Moving & Relocation' },
            { 'id': 155, 'name': 'Moving', 'parentId': 154 }
        ];
    }

}
